# server
server:
  port: 8081

# eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# spring
spring:
  application:
    name: first-service