# server
server:
  port: 0 # random port 사용 - instance 가 여러개라도 eureka dashboard 에 단일로 표기됨

# spring
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/Documents/study/spring-cloud-workspace/db/msa
    username: sa
    password:
  jpa:
    open-in-view: false
    database-platform: H2
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

decorator:
  datasource:
    p6spy:
      enable-logging: true


# eureka
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
